<?php
declare(strict_types=1);

namespace backend\wearables;

use backend\Configs;
use backend\FileSystemBasics;
use backend\fileSystem\PathsFS;
use backend\Main;
use backend\Paths;
use Throwable;

/**
 * Persists per-participant OAuth tokens, one file per (study, participant, provider),
 * encrypted at rest with libsodium secretbox using the server-config key
 * `wearables_token_key` (generated by cli/wearables_setup.php). Falls back to plaintext
 * with a marker prefix if sodium or the key is unavailable, so the feature still works
 * (with a one-time warning in the setup output).
 *
 * Token shape (decrypted JSON):
 *   {userId, provider, access_token, refresh_token, expires_at, provider_user_id, scopes, created}
 */
class WearablesTokenStore {
	const REFRESH_BUFFER_MS = 300000; // refresh when <5 min of validity remains

	/** @throws \backend\exceptions\CriticalException */
	public static function save(int $studyId, string $userId, string $provider, array $token): void {
		$folder = PathsFS::folderWearablesTokens($studyId);
		if(!is_dir($folder))
			FileSystemBasics::createFolder($folder, true);
		$payload = json_encode([
			'userId'           => $userId,
			'provider'         => $provider,
			'access_token'     => (string) ($token['access_token'] ?? ''),
			'refresh_token'    => (string) ($token['refresh_token'] ?? ''),
			'expires_at'       => (int) ($token['expires_at'] ?? Main::getMilliseconds()),
			'provider_user_id' => (string) ($token['provider_user_id'] ?? ''),
			'scopes'           => (string) ($token['scopes'] ?? ''),
			'created'          => (int) ($token['created'] ?? Main::getMilliseconds()),
		]);
		FileSystemBasics::writeFile(PathsFS::fileWearablesToken($studyId, $userId, $provider), self::encrypt($payload));
	}

	public static function get(int $studyId, string $userId, string $provider): ?array {
		return self::readTokenFile(PathsFS::fileWearablesToken($studyId, $userId, $provider));
	}

	/** Decrypt and decode a token file by absolute path (used when scanning the folder). */
	public static function readTokenFile(string $file): ?array {
		if(!file_exists($file))
			return null;
		$plain = self::decrypt((string) @file_get_contents($file));
		if($plain === null)
			return null;
		$data = json_decode($plain, true);
		return is_array($data) ? $data : null;
	}

	public static function delete(int $studyId, string $userId, string $provider): void {
		@unlink(PathsFS::fileWearablesToken($studyId, $userId, $provider));
		@unlink(PathsFS::fileWearablesData($studyId, $userId, $provider));
		@unlink(PathsFS::fileWearablesSyncState($studyId, $userId, $provider));
	}

	/** Connected provider slugs for a participant (by reading each token file). */
	public static function listProviders(int $studyId, string $userId): array {
		$out = [];
		foreach(WearablesRegistry::PROVIDERS as $name => $_) {
			if(file_exists(PathsFS::fileWearablesToken($studyId, $userId, $name)))
				$out[] = $name;
		}
		return $out;
	}

	/**
	 * Return a currently-valid access token, refreshing (and re-saving) when it is near
	 * expiry. Persisting the refreshed token immediately is essential for Withings/Oura,
	 * whose refresh tokens are single-use. Returns null when no token is stored.
	 * @throws WearablesException
	 */
	public static function getValidAccessToken(int $studyId, string $userId, string $provider, WearablesProvider $providerObj): ?string {
		$token = self::get($studyId, $userId, $provider);
		if($token === null)
			return null;
		$expiresAt = (int) ($token['expires_at'] ?? 0);
		if($expiresAt - Main::getMilliseconds() > self::REFRESH_BUFFER_MS)
			return (string) $token['access_token'];

		$refresh = (string) ($token['refresh_token'] ?? '');
		if($refresh === '')
			return (string) $token['access_token']; // nothing we can do; let the caller try
		$fresh = $providerObj->refreshToken($refresh);
		// Preserve fields the refresh response may omit (Oura drops the user id).
		$merged = array_merge($token, [
			'access_token'     => $fresh['access_token'],
			'refresh_token'    => $fresh['refresh_token'] !== '' ? $fresh['refresh_token'] : $refresh,
			'expires_at'       => $fresh['expires_at'],
			'scopes'           => $fresh['scopes'] !== '' ? $fresh['scopes'] : ($token['scopes'] ?? ''),
			'provider_user_id' => $fresh['provider_user_id'] !== '' ? $fresh['provider_user_id'] : ($token['provider_user_id'] ?? ''),
		]);
		self::save($studyId, $userId, $provider, $merged);
		return (string) $merged['access_token'];
	}

	// --- encryption --------------------------------------------------------------

	private static function key(): ?string {
		if(!function_exists('sodium_crypto_secretbox'))
			return null;
		$b64 = (string) Configs::get('wearables_token_key');
		if($b64 === '')
			return null;
		$key = base64_decode($b64, true);
		return ($key !== false && strlen($key) === SODIUM_CRYPTO_SECRETBOX_KEYBYTES) ? $key : null;
	}

	private static function encrypt(string $plain): string {
		$key = self::key();
		if($key === null)
			return 'p0:' . $plain; // plaintext fallback (server has no token key configured)
		$nonce = random_bytes(SODIUM_CRYPTO_SECRETBOX_NONCEBYTES);
		$cipher = sodium_crypto_secretbox($plain, $nonce, $key);
		return 'v1:' . base64_encode($nonce . $cipher);
	}

	private static function decrypt(string $blob): ?string {
		if(strncmp($blob, 'p0:', 3) === 0)
			return substr($blob, 3);
		if(strncmp($blob, 'v1:', 3) !== 0)
			return null;
		$key = self::key();
		if($key === null)
			return null;
		$raw = base64_decode(substr($blob, 3), true);
		if($raw === false || strlen($raw) < SODIUM_CRYPTO_SECRETBOX_NONCEBYTES)
			return null;
		$nonce  = substr($raw, 0, SODIUM_CRYPTO_SECRETBOX_NONCEBYTES);
		$cipher = substr($raw, SODIUM_CRYPTO_SECRETBOX_NONCEBYTES);
		try {
			$plain = sodium_crypto_secretbox_open($cipher, $nonce, $key);
		}
		catch(Throwable $e) {
			return null;
		}
		return $plain === false ? null : $plain;
	}
}
